import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { i18n } from "@/i18n-config";
import { cn } from "@utils";
import { Toaster } from "../components/atoms/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }))
}


export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: { lang: string }
}) {
  return (
    <html lang={params.lang}>
      <body className={cn('min-h-screen font-sans antialiased grainy', inter.className)}>
        {children}
        <Toaster />
      </body>
    </html>
  )
}
